'use client';
// components/academy/learning-room/interactions/sort-it.tsx
import {useState,type DragEvent} from 'react';
import {card,tones,type InteractionProps} from './types';
export function SortIt({data,onComplete}:InteractionProps){
 const items=data.items??[];const groups=data.groups??[];const [selected,setSelected]=useState<string|null>(null);const [assigned,setAssigned]=useState<Record<string,string>>({});const [checked,setChecked]=useState(false);
 function assign(id:string|null,group:string){if(!id||checked||!items.some(x=>x.id===id))return;setAssigned(p=>({...p,[id]:group}));setSelected(null);}
 function drop(e:DragEvent,g:string){e.preventDefault();assign(e.dataTransfer.getData('text/plain')||selected,g);}
 function verify(){if(Object.keys(assigned).length!==items.length)return;setChecked(true);const n=items.filter(x=>assigned[x.id]===x.groupId).length;onComplete({correct:n===items.length,score:Math.round(n/Math.max(1,items.length)*100)});}
 return <div><p className="mb-4 text-sm text-slate-600">{data.instruction}</p><div className="mb-4 flex flex-wrap gap-2">{items.map(x=><button key={x.id} type="button" draggable={!checked} onDragStart={e=>e.dataTransfer.setData('text/plain',x.id)} onClick={()=>setSelected(x.id)} className={`${card} text-sm ${selected===x.id?'ring-2 ring-violet-500':''}`}>{x.label}{assigned[x.id]?' ✓':''}</button>)}</div><div className="grid gap-3 sm:grid-cols-2">{groups.map((g,i)=><button type="button" key={g.id} onClick={()=>assign(selected,g.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,g.id)} className={`min-h-36 rounded-3xl p-5 text-left ${tones[i%tones.length]}`}><strong>{g.label}</strong><div className="mt-3 flex flex-wrap gap-2">{items.filter(x=>assigned[x.id]===g.id).map(x=><span key={x.id} className="rounded-lg bg-white/80 px-3 py-2 text-xs">{x.label}{checked?(x.groupId===g.id?' ✓':' ✕'):''}</span>)}</div></button>)}</div>{!checked?<button type="button" disabled={Object.keys(assigned).length!==items.length} onClick={verify} className="mt-5 rounded-xl bg-[#7566B8] px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Comprobar clasificación</button>:<div className="mt-4 rounded-xl bg-[#F2F0FA] p-4 text-sm">{items.filter(x=>assigned[x.id]===x.groupId).length} de {items.length} correctos. {items.filter(x=>assigned[x.id]!==x.groupId).map(x=><p key={x.id} className="mt-2">{x.label}: {x.feedback||`Pertenece a ${groups.find(g=>g.id===x.groupId)?.label??'otra categoría'}`}</p>)}</div>}</div>;
}
