// lib/knowledge/import/prompts/article-content-system-prompt.ts

import {
  ARTICLE_CALLOUT_PROMPT,
  ARTICLE_CHECKLIST_PROMPT,
  ARTICLE_ELEMENTS_PROMPT,
  ARTICLE_FIDELITY_PROMPT,
  ARTICLE_HTML_PROMPT,
  ARTICLE_MERMAID_PROMPT,
  ARTICLE_QUALITY_PROMPT,
  ARTICLE_ROLE_PROMPT,
  ARTICLE_SOURCES_PROMPT,
  ARTICLE_STRUCTURE_PROMPT,
  ARTICLE_UPDATE_PROMPT,
} from "./article-content-prompt-sections";

export const ARTICLE_CONTENT_SYSTEM_PROMPT = [
  ARTICLE_ROLE_PROMPT,
  ARTICLE_FIDELITY_PROMPT,
  ARTICLE_HTML_PROMPT,
  ARTICLE_STRUCTURE_PROMPT,
  ARTICLE_ELEMENTS_PROMPT,
  ARTICLE_CHECKLIST_PROMPT,
  ARTICLE_CALLOUT_PROMPT,
  ARTICLE_MERMAID_PROMPT,
  ARTICLE_SOURCES_PROMPT,
  ARTICLE_UPDATE_PROMPT,
  ARTICLE_QUALITY_PROMPT,
].join("\n\n");
